spring.application.name=skml-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


frontend.url=${FRONTEND_URL}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ===== Shop =====
invoice.shop.name=${SHOP_NAME}
invoice.shop.gst=${GST_NUMBER}
invoice.shop.address=${SHOP_ADDRESS}
invoice.shop.website=${SHOP_WEBSITE}
invoice.shop.contact=${SHOP_CONTACT}

# ===== Bank =====
invoice.bank.name=${BANK_NAME}
invoice.bank.accountName=${BANK_ACCOUNT_NAME}
invoice.bank.accountNo=${BANK_ACCOUNT_NO}
invoice.bank.ifsc=${BANK_IFSC}



# HikariCP settings for free tier stability
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.initialization-mode=never

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false


